[versions]
tg-bot = "9.1.1"
ksp = "2.3.5"
exposed = "0.61.0"
sqlite = "3.51.1.0"

kotlin = "2.3.0"

[libraries]
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
sqlite-driver = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite" }

[plugins]
telegram-bot = { id = "eu.vendeli.telegram-bot", version.ref = "tg-bot" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }